flashTill:
  db:
    host: localhost
    username: root
    password: root
    type: mysql
    name: flashTill

server:
  port: 8888
spring:
  application:
    name: Flash-Till
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${flashTill.db.host}:3306/${flashTill.db.name}?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&keepAlive=true&autoReconnect=true&autoReconnectForPools=true&connectTimeout=30000&socketTimeout=60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${flashTill.db.username}
    password: ${flashTill.db.password}
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置连接池，例如 HikariCP
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB #单文件最大
      max-request-size: 10MB #总文件最大
      enabled: true
  web:
    websocket:
      max-binary-message-size: 20MB
      max-text-message-size: 20MB

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: info
    web: info
  charset:
    console: UTF-8
    file: UTF-8
  config: classpath:logback/logback.xml

swagger:
  enable: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-not-delete-value: 0
      logic-delete-value: "null"
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
